### ISSUE TITLE
Add xbar=mean(y) and xbar=0 methods

### ISSUE THREAD

**Issue by neerajt** [keshlab/returnAdj.R#6]
The current method that translates the output vector using the linear model's intercept is unstable. There are two reasonable alternatives:
- [Dukart et al.](http://journals.plos.org/plosone/article?id=10.1371/journal.pone.0022193) propose using just the residuals as the output vector, with no translation, effectively putting the mean to zero. 
- An option we considered in the past is to translate using the mean of the original vector, putting the mean of the output vector to the observed mean.

Proposed fix: Add methods and a `method=` argument, pick a method as default.

**Comment by surajsarvode** [comment]
Neeraj,

Ive incorporated this change and shared the script. Let me know what you think. This seems fairly straight-forward with a few if statements thrown in. I have sent the script to you. Let me know what you think. I test-ran with some data and cheeked it. They appear fine.

**Comment by neerajt** [comment]
Thanks, Suraj. This looks great!

Cheers :beers:
